title: Fangzhou Sun
author: Fangzhou Sun
description: Ph.D. candidate in Operations Research at Virginia Tech
url: http://sun.fangzhou.me
timezone: America/New_York

email: fzsun@vt.edu
linkedin: fangzhousun

markdown: kramdown

tracking_id: UA-49265936-3

sass:
  style: compressed
  sass_dir: _sass

nav:
        #  - name: Resume
        #    link: fsun-vita.pdf
    
